# Debugging Python code

Go through the exercises below. 

- Each exercise contains some code with **one or more mistakes** on it. 
- The mistakes can either prompt an error or not.
- There might be multiple ways to fix the mistakes.
- Improving the code readibility is also encourage.

In [1]:
# data creation
beatles = ["John Lennon", "Paul McCartney", "George Harrison", "Ringo Star"]

numbers = [1, 2, 3, 4, 5]

capitals = {"Germany": "Berlin", 
            "Russia": "Moscow",
            "France": "Paris",
            "China": "Beijing",
            "Egypt": "Cairo",
            "Brazil": "Sao Paulo"
            }

top_profitable_films = {
    "Film": ["Avengers: Endgame", "Avatar", "Titanic", "Star Wars: The Force Awakens", "Jurassic World",
             "The Lion King", "The Avengers", "Frozen II", "Frozen", "Beauty and the Beast"],
    "Year": ["2019", "2007", "1997", "2015", "2015", "2019", "2012", "2019", "2013", "2017"],
    "Worldwide Gross (in billions)": ["2.798", "2.789", "2.194", "2.073", "1.673", "1.656", "1.519", 
                                      "1.450", "1.276", "1.263"]
    }

## Exercise 1:

In [2]:
for c in Capitals.keys():
  print(f"{c} is the capital of {Capitals[c]}")

NameError: ignored

In [3]:
# step 1 - C to c
for c in capitals.keys():
  print(f"{c} is the capital of {capitals[c]}")

Germany is the capital of Berlin
Russia is the capital of Moscow
France is the capital of Paris
China is the capital of Beijing
Egypt is the capital of Cairo
Brazil is the capital of Sao Paulo

In [4]:
# step 2
for c in capitals.keys():
  print(f"{capitals[c]} is the capital of {c}")

Berlin is the capital of Germany
Moscow is the capital of Russia
Paris is the capital of France
Beijing is the capital of China
Cairo is the capital of Egypt
Sao Paulo is the capital of Brazil

In [5]:
# step 3 - better variables
for country in capitals.keys():
  print(f"{capitals[country]} is the capital of {country}")

Berlin is the capital of Germany
Moscow is the capital of Russia
Paris is the capital of France
Beijing is the capital of China
Cairo is the capital of Egypt
Sao Paulo is the capital of Brazil

## Exercise 2:
Let's imagine we want to show our love for Ringo Star and print a love statement for him as many times as numbers are in the `numbers` list. For all Beatles who are not Ringo, we want to print as many times a hate statement. The output should look like this:

```
I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!
```

In [ ]:
for beatle in beatles:
  if beatle = "Ringo Star":
    for n in numbers:
      print(f"I love {beatle}!")
  if beatle != "Ringo Star":
    print(f"I hate {beatle}!")
      print("\n")

SyntaxError: ignored

In [9]:
for n in numbers:
  for beatle in beatles:
    if beatle == "Ringo Star":
      print(f"I love {beatle}!")
    if beatle != "Ringo Star":
      print(f"I hate {beatle}!")
  print("\n")

I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!

In [8]:
for n in numbers:
  for beatle in beatles:
    if beatle == "Ringo Star":
      print(f"I love {beatle}!")
    else:
      print(f"I hate {beatle}!")
  print("\n")

I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!


I hate John Lennon!
I hate Paul McCartney!
I hate George Harrison!
I love Ringo Star!

## Exercise 3:

In [ ]:
top_profitable_films = pd.DataFrame(top_profitable_films)
top_profitable_films.head

NameError: ignored

In [13]:
top_profitable_films.columns

Index(['Film', 'Year', 'Worldwide Gross (in billions)'], dtype='object')

In [15]:
import pandas as pd
top_profitable_films = pd.DataFrame(top_profitable_films)
top_profitable_films.head()

                           Film  Year Worldwide Gross (in billions)
0             Avengers: Endgame  2019                         2.798
1                        Avatar  2007                         2.789
2                       Titanic  1997                         2.194
3  Star Wars: The Force Awakens  2015                         2.073
4                Jurassic World  2015                         1.673

## Exercise 4:

In [ ]:
top_films_df[top_films_df["Film"]=="Avatar"]["Year"] = "2009"

<ipython-input-44-a69360be8c6c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_films_df[top_films_df["Film"]=="Avatar"]["Year"] = 2009

In [18]:
top_profitable_films.loc[top_profitable_films["Film"]=="Avatar","Year"] = '2009'

## Exercise 5:

We want to get the average gross profit of all films:

In [ ]:
top_films_df["Worldwide Gross (in billions)"].avg()

AttributeError: ignored

In [20]:
top_profitable_films["Worldwide Gross (in billions)"].astype(float).mean().round(1)

1.9

In [21]:
top_profitable_films["Worldwide Gross (in billions)"] = pd.to_numeric(top_profitable_films["Worldwide Gross (in billions)"])

In [22]:
top_profitable_films["Worldwide Gross (in billions)"].mean()

1.8691000000000002